export interface BookEntry {
  volume: string;
  volumeAbbrev: string;
  book: string;
  filename: string;
}

export const BOOK_ORDER: BookEntry[] = [
  // Old Testament (39 books)
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Genesis", filename: "Old_Testament_-_Genesis.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Exodus", filename: "Old_Testament_-_Exodus.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Leviticus", filename: "Old_Testament_-_Leviticus.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Numbers", filename: "Old_Testament_-_Numbers.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Deuteronomy", filename: "Old_Testament_-_Deuteronomy.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Joshua", filename: "Old_Testament_-_Joshua.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Judges", filename: "Old_Testament_-_Judges.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Ruth", filename: "Old_Testament_-_Ruth.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "1 Samuel", filename: "Old_Testament_-_1_Samuel.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "2 Samuel", filename: "Old_Testament_-_2_Samuel.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "1 Kings", filename: "Old_Testament_-_1_Kings.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "2 Kings", filename: "Old_Testament_-_2_Kings.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "1 Chronicles", filename: "Old_Testament_-_1_Chronicles.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "2 Chronicles", filename: "Old_Testament_-_2_Chronicles.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Ezra", filename: "Old_Testament_-_Ezra.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Nehemiah", filename: "Old_Testament_-_Nehemiah.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Esther", filename: "Old_Testament_-_Esther.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Job", filename: "Old_Testament_-_Job.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Psalms", filename: "Old_Testament_-_Psalms.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Proverbs", filename: "Old_Testament_-_Proverbs.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Ecclesiastes", filename: "Old_Testament_-_Ecclesiastes.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Song of Solomon", filename: "Old_Testament_-_Song_of_Solomon.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Isaiah", filename: "Old_Testament_-_Isaiah.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Jeremiah", filename: "Old_Testament_-_Jeremiah.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Lamentations", filename: "Old_Testament_-_Lamentations.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Ezekiel", filename: "Old_Testament_-_Ezekiel.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Daniel", filename: "Old_Testament_-_Daniel.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Hosea", filename: "Old_Testament_-_Hosea.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Joel", filename: "Old_Testament_-_Joel.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Amos", filename: "Old_Testament_-_Amos.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Obadiah", filename: "Old_Testament_-_Obediah.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Jonah", filename: "Old_Testament_-_Jonah.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Micah", filename: "Old_Testament_-_Micah.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Nahum", filename: "Old_Testament_-_Nahum.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Habakkuk", filename: "Old_Testament_-_Habakkuk.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Zephaniah", filename: "Old_Testament_-_Zephaniah.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Haggai", filename: "Old_Testament_-_Haggai.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Zechariah", filename: "Old_Testament_-_Zechariah.md" },
  { volume: "Old Testament", volumeAbbrev: "OT", book: "Malachi", filename: "Old_Testament_-_Malachi.md" },

  // New Testament (27 books)
  { volume: "New Testament", volumeAbbrev: "NT", book: "Matthew", filename: "New_Testament_-_Matthew.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Mark", filename: "New_Testament_-_Mark.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Luke", filename: "New_Testament_-_Luke.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "John", filename: "New_Testament_-_John.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Acts", filename: "New_Testament_-_Acts.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Romans", filename: "New_Testament_-_Romans.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "1 Corinthians", filename: "New_Testament_-_1_Corinthians.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "2 Corinthians", filename: "New_Testament_-_2_Corinthians.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Galatians", filename: "New_Testament_-_Galatians.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Ephesians", filename: "New_Testament_-_Ephesians.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Philippians", filename: "New_Testament_-_Philippians.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Colossians", filename: "New_Testament_-_Collosians.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "1 Thessalonians", filename: "New_Testament_-_1_Thessalonians.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "2 Thessalonians", filename: "New_Testament_-_2_Thessalonians.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "1 Timothy", filename: "New_Testament_-_1_Timothy.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "2 Timothy", filename: "New_Testament_-_2_Timothy.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Titus", filename: "New_Testament_-_Titus.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Philemon", filename: "New_Testament_-_Philemon.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Hebrews", filename: "New_Testament_-_Hebrews.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "James", filename: "New_Testament_-_James.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "1 Peter", filename: "New_Testament_-_1_Peter.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "2 Peter", filename: "New_Testament_-_2_Peter.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "1 John", filename: "New_Testament_-_1_John.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "2 John", filename: "New_Testament_-_2_John.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "3 John", filename: "New_Testament_-_3_John.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Jude", filename: "New_Testament_-_Jude.md" },
  { volume: "New Testament", volumeAbbrev: "NT", book: "Revelation", filename: "New_Testament_-_Revelation.md" },

  // Book of Mormon (16 books — excludes Introduction_and_Witnesses)
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "1 Nephi", filename: "Book_of_Mormon_-_1_Nephi.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "2 Nephi", filename: "Book_of_Mormon_-_2_Nephi.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Jacob", filename: "Book_of_Mormon_-_Jacob.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Enos", filename: "Book_of_Mormon_-_Enos.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Jarom", filename: "Book_of_Mormon_-_Jarom.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Omni", filename: "Book_of_Mormon_-_Omni.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Words of Mormon", filename: "Book_of_Mormon_-_Words_of_Mormon.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Mosiah", filename: "Book_of_Mormon_-_Mosiah.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Alma", filename: "Book_of_Mormon_-_Alma.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Helaman", filename: "Book_of_Mormon_-_Helaman.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "3 Nephi", filename: "Book_of_Mormon_-_3_Nephi.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "4 Nephi", filename: "Book_of_Mormon_-_4_Nephi.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Mormon", filename: "Book_of_Mormon_-_Mormon.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Ether", filename: "Book_of_Mormon_-_Ether.md" },
  { volume: "Book of Mormon", volumeAbbrev: "BoM", book: "Moroni", filename: "Book_of_Mormon_-_Moroni.md" },

  // Doctrine and Covenants (1 file)
  { volume: "Doctrine and Covenants", volumeAbbrev: "D&C", book: "Doctrine and Covenants", filename: "Doctrine_and_Covenants.md" },

  // Pearl of Great Price (5 books)
  { volume: "Pearl of Great Price", volumeAbbrev: "PoGP", book: "Moses", filename: "Pearl_of_Great_Price_-_Moses.md" },
  { volume: "Pearl of Great Price", volumeAbbrev: "PoGP", book: "Abraham", filename: "Pearl_of_Great_Price_-_Abraham.md" },
  { volume: "Pearl of Great Price", volumeAbbrev: "PoGP", book: "Joseph Smith\u2014Matthew", filename: "Pearl_of_Great_Price_-_Joseph_Smith_Matthew.md" },
  { volume: "Pearl of Great Price", volumeAbbrev: "PoGP", book: "Joseph Smith\u2014History", filename: "Pearl_of_Great_Price_-_Joseph_Smith_History.md" },
  { volume: "Pearl of Great Price", volumeAbbrev: "PoGP", book: "Articles of Faith", filename: "Pearl_of_Great_Price_-_The_Articles_of_Faith.md" },
];
